### ISSUE TITLE
CLI: error while loading shared libraries: libproc_macro: cannot open shared object file

### ISSUE THREAD

**Issue by Avi-D-coder** [graphql-rust/graphql-client#185]
`rustc 1.32.0-nightly (9fefb6766 2018-11-13)`

## Steps to reproduce:

```sh
git clone --depth 1 https://github.com/graphql-rust/graphql-client.git
cargo build && cargo build --release # Just to cover the bases
cd graphql_client_cli
cargo install # --debug makes no difference
graphql-client --help
```
### Output:
```
graphql-client: error while loading shared libraries: libproc_macro-6c2e946fbc2e5b5e.so: cannot open shared object file: No such file or directory
```

**Comment by tomhoule** [comment]
Temporarily, you can run it with `cargo run` from the source directory, that works for me. I haven't used the CLI a lot so I don't have a cleaner solution. This will be permanently solved by this PR: https://github.com/rust-lang/rust/pull/49219#issuecomment-438379259

Maybe @h-michael has a better solution?

**Comment by h-michael** [comment]
This should occur only nightly build.
So you should build cli with stable rust until that PR merged.

**Comment by h-michael** [comment]
merged: https://github.com/rust-lang/rust/pull/49219

**Comment by tomhoule** [comment]
Great news!

**Comment by theduke** [comment]
This is still an issue with latest stable.

Maybe the README should mention that the CLI only supports nightly right now.

**Comment by theduke** [comment]
Oh, actually I just noticed: even on nightly the built binary does not work!

It only works with `cargo run`. Executing `target/debug/graphql-client` still gives the same error.

**Comment by h-michael** [comment]
@theduke
Thank you for your report.
I 'll try it later.

**Comment by mathstuf** [comment]
Is this still an issue?

**Comment by tomhoule** [comment]
I haven't tried in a very long time! It would be nice to clarify this.
